import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import ClientProvider from "@/components/layout/client-provider";
import { AppContextProvider } from "@/components/layout/context-provider";
import QueryProvider from "@/components/layout/query-provider";
import ToastProvider from "@/components/layout/toast-provider";

const fDefault = Geist({
  variable: "--font-default",
  subsets: ["latin"],
});

const fPrimary = Geist_Mono({
  variable: "--font-primary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Core",
  description: "Generated by Jee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${fDefault.variable} ${fPrimary.variable} antialiased`}
        >
          <AppContextProvider>
            <ToastProvider />
            <QueryProvider>
              <ClientProvider>{children}</ClientProvider>
            </QueryProvider>
          </AppContextProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
